### ISSUE TITLE
Back button of any article does not link properly - 

### ISSUE THREAD

**Issue by bernatferragut** [P0WEX/Gesko#6]
Example click on the first article. once there on the top left if you click on the back button a 404 is shown.

**Comment by P0WEX** [comment]
I can't replicate your error, can you please provide some screenshot or Gif?

**Comment by jjvdhoven** [comment]
@P0WEX I had the same issue and what seems to happen is that when you inspect the HTML a slash ( "/" ) is missing at the end of the base url. I managed to fix it as it seems to just be a configuration error by the user :^)

If the user forgets to put the path in the __config.yml under this section it will throw the error @bernatferragut is most likely referring to:

```
defaults:
  -
    scope:
      path: "/Blog"
    values:
      layout: "default"
  -
    scope:
      path: "/Blog"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "/Blog"
      type: "posts"
    values:
      layout: "post"
```
